### ISSUE TITLE
How do you use the tsf library with visual studio debug output?

### ISSUE THREAD

**Issue by DavidSM64** [bmharper/WindowsDesktopDuplicationSample#2]
In this sample you use the TSF library for printing out to `stdout`, but that doesn't usually work with Win32 gui applications. You would normally have to use `OutputDebugString` instead. I can't seem to get any output from `tfs::print` or `tfs::fmt`. How do you have your environment setup to make this work with visual studio?

**Comment by bmharper** [comment]
You're right. It's been many years, but I have a vague recollection of being able to have a Win32 app with a console and GUI, but I can't figure out how to do that now. Setting the Linker Subsystem setting to CONSOLE gives weird behaviour, and no GUI, so that doesn't work.
Anyway - there is only one call to tsf::print, and you're right that it goes nowhere. All of the other calls to `tsf` are `tsf::fmt`, which returns a string (for error message).

OK.. I've googled around a bit, and this does work:
```cpp
// Inside stdafx.h
#define _CRT_SECURE_NO_WARNINGS 1

// Inside wWinMain
AllocConsole();
freopen("CONOUT$", "w", stdout); 
```

**Comment by DavidSM64** [comment]
Ah, thank you! That indeed works perfectly.

Also, wanted to say thanks for creating this example. I was capturing the desktop using BitBlt/StretchBlt before and it was _**slow**_ with my 2880x1800 screen. Now it takes about 6ms with this solution. :)

**Comment by bmharper** [comment]
Glad it helps!
